name: CI/CD

on:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: ./lein test
    
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker image
      run: docker build -t n0th1ngn355/mire:latest .
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push Docker image to Docker Hub
      run: docker push n0th1ngn355/mire:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          podman pull n0th1ngn355/mire:latest
          podman stop mire || true
          podman rm mire || true
          podman run -d --name mire -p 3333:3333 n0th1ngn355/mire:latest
